//ATLETI
GET http://localhost:3001/athletes/byTeamRequest?requestedTeam=6542b0083f83da4168a24a7b
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDAxMTYxMjNmOGM1NDBkYTE5YWI0YiIsIm5hbWUiOiJJdmFuIiwic3VybmFtZSI6IlpheXRzZXYiLCJlbWFpbCI6ImVtYUBnbWFpbC5jb20iLCJpYXQiOjE2OTg2OTc5NDksImV4cCI6MTY5ODc4NDM0OX0.4s8PaAyJ7F9dzmx4cdRLAE3VsQ66wTL3Irwy2lwMKTU 

####
GET http://localhost:3001/athletes/byId/

####
POST http://localhost:3001/athletes/create HTTP/1.1
Content-Type: application/json

{
  "name":"Daniele",
  "surname":"Lavia",
  "email":"dani@mail.com",
  "age":23 ,
  "cover":"https://volleybox.net/media/upload/players/1683112106gag0n.png",
  "password":"0000",
  "role":"outside-hitter",
  "requestedTeam":"6542b0083f83da4168a24a7b",
  "team":null
}

####
PATCH http://localhost:3001/athletes/update/654f8439f578e0b32fe81c2d HTTP/1.1
Content-Type: application/json

{
  "team":"6542b0083f83da4168a24a7b",
  "requestedTeam":null
}

####
DELETE http://localhost:3001/athletes/delete/654934362c5b29f818928b78 HTTP/1.1
//
//
//
//SQUADRE
####
GET http://localhost:3001/teams

####
GET http://localhost:3001/teams/byId/653d7e868f87a126aacf7838

####
POST http://localhost:3001/teams/create HTTP/1.1
Content-Type: application/json

{
  "name":"SIR Perugia",
  "email":"pallavolo@gmail.com",
  "password":"0000"
}

####
PATCH http://localhost:3001/teams/update/653d7e868f87a126aacf7838 HTTP/1.1
Content-Type: application/json

{
  "email":"pbologna@info.com"
}

####
DELETE http://localhost:3001/teams/delete/653d7e868f87a126aacf7838 HTTP/1.1
//
//
//
// LOGIN
####
POST http://localhost:3001/loginAthlete
Content-Type: application/json

{
  "email":"ema@gmail.com",
  "password":"0000"
}

####
POST http://localhost:3001/loginTeam
Content-Type: application/json

{
  "email":"pallavolo@gmail.com",
  "password":"0000"
}


//

####
GET http://localhost:3001/events/byTeam?team=6542b0083f83da4168a24a7b&page=1 HTTP/1.1
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDJiMDA4M2Y4M2RhNDE2OGEyNGE3YiIsIm5hbWUiOiJNb2RlbmEgVm9sbGV5IiwiZW1haWwiOiJtb2RlbmFAbWFpbC5jb20iLCJpYXQiOjE3MDAwODUxNTMsImV4cCI6MTcwMDE3MTU1M30.QSsGHFoLeN9qJnS7Cl2MD00CkagNHVEzVkMxyJwttgc

####
POST http://localhost:3001/events/create HTTP/1.1
Content-Type: application/json

{
  "title":"Partita Sabato 1/12",
  "content":"Modena Volley vs LUBE Civitanova",
  "team":"6542b0083f83da4168a24a7b"
}


